const SET_CATALOG_ITEMS = 'Catalog/SET-CATALOG-ITEMS'
const SET_POPULARS  = 'Catalog/SET-POPULARS'
const SET_NOVELTIES = 'Catalog/SET-NOVELTIES'
const SET_PAGE = 'Catalog/SET-PAGE'
const SET_COUNT_OF_PAGE_ITEMS = 'Catalog/SET-COUNT-OF-PAGE-ITEMS'
const UPDATE_CATALOG_ITEMS = 'Catalog/UPDATE-CATALOG-ITEMS'
const SET_CHECKED_PROPERTIES = 'Catalog/SET-CHECKED-VALUES'
const SET_IS_FETCHING = 'Catalog/SET-IS-FETCHING'

export default {
    SET_CATALOG_ITEMS,
    SET_NOVELTIES,
    SET_POPULARS,
    SET_COUNT_OF_PAGE_ITEMS,
    SET_PAGE,
    UPDATE_CATALOG_ITEMS,
    SET_CHECKED_PROPERTIES,
    SET_IS_FETCHING
}