const SET_PAGES = 'Reader/SET-PAGES'
const SET_READING_STYLE = 'Reader/SET-READING-STYLE'
const SET_TYPE_OF_PAGE_INSERT = 'Reader/SET-TYPE-OF-PAGE-INSERT'
const SET_CONTAINER_WIDTH = 'Reader/SET-CONTAINER-WIDTH'


export default {
    SET_PAGES,
    SET_READING_STYLE,
    SET_TYPE_OF_PAGE_INSERT,
    SET_CONTAINER_WIDTH
}