
const SET_SELECTED_GENRE = 'Catalog/Filter/SET-GENRES'
const SET_SELECTED_AGE_DISTINCTION = 'Catalog/Filter/SET-SELECTED-AGE-DISTINCTIONS'
const SET_SELECTED_TYPE = 'Catalog/Filter/SET-SELECTED-TYPES'

const SET_ALL_AVAILABLE_DATA = 'Catalog/Filter/SET-AVAILABLE-DATA'
export default {
    SET_SELECTED_TYPE,
    SET_SELECTED_GENRE,
    SET_SELECTED_AGE_DISTINCTION,
    SET_ALL_AVAILABLE_DATA
}