const SET_PROFILE_INFO ='Profile/SET-PROFILE-INFO'
const SET_RATING_LIST='Profile/SET-RATING-LIST'
const SET_RATING_LIST_ITEMS_ELEMENTS = 'Profile/SET-RATING-LIST-ITEMS-ELEMENTS'
export default {
    SET_PROFILE_INFO,
    SET_RATING_LIST,
    SET_RATING_LIST_ITEMS_ELEMENTS
}
