const SET_ANIME_INFO = 'ContentAnime/SET-ANIME-INFO'
const SET_CURRENT_SERIES_NUMBER = 'ContentAnime/SET-CURRENT-SERIES-NUMBER'
const SET_CURRENT_SERIES_DATA = 'ContentAnime/SET-CURRENT-SERIES-DATA'
const SET_CURRENT_VOICE_ACTOR ='ContentAnime/SET-CURRENT-VOICE-ACTOR'
const SET_CURRENT_CONTENT  = 'ContentAnime/SET-CURRENT-CONTENT'
const SET_AVAILABLE_CONTENT  = 'ContentAnime/SET-AVAILABLE-CONTENT'
const SET_RELATED_CONTENT = 'СontentAnime/SET-RELATED-CONTENT'

export default {
    SET_ANIME_INFO,
    SET_CURRENT_SERIES_NUMBER,
    SET_CURRENT_SERIES_DATA,
    SET_CURRENT_VOICE_ACTOR,
    SET_CURRENT_CONTENT,
    SET_AVAILABLE_CONTENT,
    SET_RELATED_CONTENT
}